### ISSUE TITLE
error: ‘waitKeyEx’ is not a member of ‘cv’

### ISSUE THREAD

**Issue by sabpap** [AlexeyAB/Yolo_mark#20]
hello,

I tried to compile using both opencv 3.3 and 2.4. and i keep getting the same error:
![image](https://user-images.githubusercontent.com/33451452/34124448-989ca9f4-e43b-11e7-9916-4cd855afb6bc.png)

**Comment by AlexeyAB** [comment]
@sabpap Hi,

I fixed it: https://github.com/AlexeyAB/Yolo_mark/commit/d0f23d83dbf540ba3d9c8657df6509df1bd7ac29
Just update your code from this repo.

I tested it on both OpenCV 2.4.13 and OpenCV 3.3.1 on Windows and Linux.

**Comment by sabpap** [comment]
thanks a lot!!fixed...

**Comment by aidinhass** [comment]
Hi @AlexeyAB, I'm getting the same issue with opencv 3.4.

![screenshot from 2018-04-13 01-44-34](https://user-images.githubusercontent.com/33791593/38720662-bb0c2de4-3ebc-11e8-82fc-47a80dc6d80d.png)

**Comment by alexanderfrey** [comment]
Same error here....

**Comment by aidinhass** [comment]
Found a temp way to get around this: just go back from `cv::waitKeyEx` to` cv::waitKey`. No idea why, but worked for me.

**Comment by AlexeyAB** [comment]
@sabpap @aidinhass @alexanderfrey @lovexytoo 
I fixed it.

Added `#include <opencv2/highgui.hpp>` where is `waitKeyEx()` now: https://github.com/opencv/opencv/blob/7e5581cd86bfa82de5aaccd69f871cd4ebd2bf5d/modules/highgui/include/opencv2/highgui.hpp#L330

**Comment by alexanderfrey** [comment]
Thanks for the fix but unfortunately still does not work. When I change call to waitKeyEx() -> waitKey() in main.cpp in line 143 and 575 compilation runs through though. Shall I create a PR ?

**Comment by AlexeyAB** [comment]
@alexanderfrey No, PR is not necessary here, since in many cases, the `waitKey()` does not work, and it requires the `waitKeyEx()`.

* What OpenCV version do you use?
* What Operation System and GCC version do you use?
* Can you show screenshot of the error?

**Comment by ayooshkathuria** [comment]
Same error here. Using OpenCV 3.4.1 and Python 3.6.4

**Comment by AlexeyAB** [comment]
@ayooshkathuria 

* What version of operation system do you use?

* Check, do you have definition of `CV_EXPORTS_W int waitKeyEx(int delay = 0);` in the file `include/opencv2/highgui.hpp` in the source code of OpenCV? https://github.com/opencv/opencv/blob/3.4/modules/highgui/include/opencv2/highgui.hpp#L330

**Comment by otluiz** [comment]
Hello people!!

the function cv::waitKey(0); 
...............................^........
You need upercase: "K";  waitKey(0);
