### ISSUE TITLE
Error with compiling

### ISSUE THREAD

**Issue by KGWON** [AlexeyAB/Yolo_mark#69]
ubuntu 16.04, python 3.6

caitech@caitech-desktop:~/Yolo_mark$ make
Scanning dependencies of target yolo_mark
[ 50%] Building CXX object CMakeFiles/yolo_mark.dir/main.cpp.o
[100%] Linking CXX executable yolo_mark
/usr/bin/ld: warning: libicui18n.so.58, needed by //home/caitech/anaconda3/lib/libQt5Core.so.5, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libicuuc.so.58, needed by //home/caitech/anaconda3/lib/libQt5Core.so.5, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libicudata.so.58, needed by //home/caitech/anaconda3/lib/libQt5Core.so.5, not found (try using -rpath or -rpath-link)
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `u_errorName_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucal_setMillis_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_getAlias_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucal_inDaylightTime_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `u_strToLower_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_getStandardName_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `u_strToUpper_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_setSubstChars_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_getMaxCharSize_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucal_getTimeZoneDisplayName_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_fromUnicode_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_open_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_getDefaultName_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucal_getDefaultTimeZone_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucal_clone_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucal_getDSTSavings_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucol_strcoll_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_close_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_countAvailable_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucal_openCountryTimeZones_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucol_open_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_compareNames_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucal_close_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_getAvailableName_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucal_openTimeZoneIDEnumeration_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucal_open_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucol_setAttribute_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucal_openTimeZones_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `uenum_close_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_countAliases_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucol_close_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucol_getSortKey_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucal_get_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `uenum_next_58'
//home/caitech/anaconda3/lib/libQt5Core.so.5: undefined reference to `ucnv_toUnicode_58'
collect2: error: ld returned 1 exit status
CMakeFiles/yolo_mark.dir/build.make:151: recipe for target 'yolo_mark' failed
make[2]: *** [yolo_mark] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/yolo_mark.dir/all' failed
make[1]: *** [CMakeFiles/yolo_mark.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

How to solve this error messages?

**Comment by CormacAsGaeilge** [comment]
I'm hitting a similar error on compilation. I am trying to compile on Ubuntu 18.04. I think it's in relation to OpenCV but I'm not totally confident.

**Comment by kinreehou** [comment]
I ran into the same problem when compiling orb-slam on Ubuntu 16.04

**Comment by LongruiDong** [comment]
> I ran into the same problem when compiling orb-slam on Ubuntu 16.04

Hey ,Have you solved it?
