### ISSUE TITLE
error: ‘SparsePyrLKOpticalFlow’ is not a member of ‘cv’

### ISSUE THREAD

**Issue by filmnamu** [AlexeyAB/Yolo_mark#158]
hello,
I tried to compile using opencv 2.4.11 and i keep getting the 
![Screenshot from 2019-09-11 18-22-48](https://user-images.githubusercontent.com/4544730/64685279-ac89cf00-d4c1-11e9-9eb6-a72766c18f90.png)

**Comment by PlanNoa** [comment]
window 10, opencv 3.4.7 and faced same problem.

**Comment by yojayc** [comment]
> hello,
> I tried to compile using opencv 2.4.11 and i keep getting the
> ![Screenshot from 2019-09-11 18-22-48](https://user-images.githubusercontent.com/4544730/64685279-ac89cf00-d4c1-11e9-9eb6-a72766c18f90.png)

Have you sovled the problem yet?

**Comment by PlanNoa** [comment]
I got same error in opencv 3.4.7 but I could solve this problem in 2.4.13 on windows 10.

**Comment by filmnamu** [comment]
The problem in ubuntu was not solved, but no error occurred in windows 10.

**Comment by TidelyPom** [comment]
It seems that in opencv 3.1.0 ‘SparsePyrLKOpticalFlow’ is a member of cv::cuda, which means that I need to compile opencv with the cuda option activated. Does recompiling opencv with cuda, modifying the main.cpp by adding #include "cudaoptflow.hpp" and replacing cv::SparsePyrLKOpticalFlow by cv::cuda::SparsePyrLKOpticalFlow solves the problem (at least if you have a gpu) ?

**Comment by isabelapt** [comment]
I am with the same problem

**Comment by ambr89** [comment]
Me too!

**Comment by scamianbas** [comment]
Hi all, got the same problem, the last working commit for me is 1ecd253d4e2ef04fd11aee60338ed109eb1129bf "Added O - button to copy previous bboxes with object tracking"

**Comment by yangyoungLive** [comment]
When I using opencv 3.1.x,  same error. change to opencv 4.1.x, it's solved!
